
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT

#    view:
#      prefix: /templates/order/
#      suffix: .ftl

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #为空不返回
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  servlet:
    context-path: /sell


#  hibernate:
#    dialect: org.hibernate.dialect.MySQL5Dialect
#logging:
#  pattern:
#    console: "d% - %msg%n"
wechat:
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx
mybatis:
  mapper-locations: classpath:mapper/*.xml