spring:
  cloud:
    stream:
      bindings:
        output_channel:
          destination: exchange-3
          group: queue-3
          binder: rabbit_cluster
      binders:
        rabbit_cluster:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.2.203
                port: 5672
                username: guest
                password: guest
                virtual-host: /
  application:
    name: producer
server:
  port: 8081
  servlet:
    context-path: /producer